### ISSUE TITLE
Would like to take over mod

### ISSUE THREAD

**Issue by linuxgurugamer** [kujuman/StrutFinder#2]
Hi,

It seems that you aren't going to be continuing this mod, could you give me permission to take it over?  The current license you have is ARR, which prevents me from doing that.

Thanks

**Comment by kujuman** [comment]
sorry for the very slow response. if you're still interested, let me know and we can just figure out the best way to work out the legal stuff--mostly if i open it up i want to change it so it's open permanently, need to think best way to do it.

**Comment by linuxgurugamer** [comment]
Sure, although I've just recently added similar functionality to Part Wizard (not my mod, but for my own use)
I would say that the easiest way to do this would be to change/add the license to either a GPL or other open-source license, and I could then fork it and release it for 1.2

**Comment by linuxgurugamer** [comment]
Just a bump, I can't do anything until the license is changed
